services:
  - type: web
    name: php-app
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: >
      sh -c "php-fpm & nginx -g 'daemon off;'"